# Generated by Django 3.2.12 on 2023-03-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='programme_name',
        ),
    ]
