# Generated by Django 3.2.12 on 2023-03-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
