# Generated by Django 3.2.12 on 2023-03-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='0'),
        ),
    ]
