# Generated by Django 3.2.12 on 2023-03-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
